<# :
@echo off
set "_ps1=%TEMP%\%~n0.ps1"
copy /y "%~f0" "%_ps1%" >nul
PowerShell -NoProfile -ExecutionPolicy Bypass -File "%_ps1%"
del "%_ps1%"
exit /b %ERRORLEVEL%
#>

# Cursor Installer: {{SCHEME_NAME}} by {{PROVIDER}}
# Generated by Cursor Installer Creator

# Ensure running as admin
if (-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Start-Process PowerShell -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`"" -Verb RunAs -Wait
    exit
}

$ErrorActionPreference = 'Stop'

# Cursor data: filename mapped to gzip-compressed base64 content
$cursors = @{
    {{CURSORS_DICT}}
}

# INF file content
$infContent = @'
{{INF_CONTENT}}
'@

# Console header
Write-Host ''
Write-Host '==========================================' -ForegroundColor Cyan
Write-Host '  Cursor Installer: {{SCHEME_NAME}}' -ForegroundColor Cyan
Write-Host '  Provider: {{PROVIDER}}' -ForegroundColor Cyan
Write-Host '==========================================' -ForegroundColor Cyan
Write-Host ''

# Installation
$tempDir = Join-Path $env:TEMP ([System.Guid]::NewGuid().ToString())
$keepTempDir = $false
New-Item -ItemType Directory -Path $tempDir | Out-Null
Write-Host "Working folder: $tempDir" -ForegroundColor DarkGray
Write-Host ''

try {
    # Step 1: decode cursor files
    Write-Host '[1/3] Extracting cursor files...' -ForegroundColor Yellow
    $cursorIndex = 0
    foreach ($entry in $cursors.GetEnumerator()) {
        $cursorIndex++
        Write-Host "      [$cursorIndex/$($cursors.Count)] $($entry.Key)" -ForegroundColor Gray
        $compressed = [System.Convert]::FromBase64String($entry.Value)
        $ms = New-Object System.IO.MemoryStream(, $compressed)
        $gz = New-Object System.IO.Compression.GZipStream($ms, [System.IO.Compression.CompressionMode]::Decompress)
        $out = New-Object System.IO.MemoryStream
        $gz.CopyTo($out)
        [System.IO.File]::WriteAllBytes((Join-Path $tempDir $entry.Key), $out.ToArray())
    }
    Write-Host ''

    # Step 2: write INF file
    Write-Host '[2/3] Writing install file...' -ForegroundColor Yellow
    $infPath = Join-Path $tempDir 'install.inf'
    [System.IO.File]::WriteAllText($infPath, $infContent, [System.Text.Encoding]::UTF8)
    Write-Host "      $infPath" -ForegroundColor Gray
    Write-Host ''

    # Step 3: run installer
    # Note: setupapi shows its own error dialog on failure and always exits 0,
    # so we verify by checking the registry after the call.
    Write-Host '[3/3] Installing cursor scheme...' -ForegroundColor Yellow
    $rundll = Join-Path $env:SystemRoot 'System32\rundll32.exe'
    $rundllArgs = 'setupapi,InstallHinfSection DefaultInstall 132 .\install.inf'
    Write-Host "      cd $tempDir" -ForegroundColor Gray
    Write-Host "      rundll32 $rundllArgs" -ForegroundColor Gray
    Push-Location $tempDir
    try {
        $proc = Start-Process -FilePath $rundll -ArgumentList $rundllArgs -Wait -PassThru
    }
    finally {
        Pop-Location
    }
    Write-Host "      Exit code: $($proc.ExitCode)" -ForegroundColor Gray
    Write-Host ''

    # Verify installation by checking registry
    $schemeKey = Get-Item 'HKCU:\Control Panel\Cursors\Schemes' -ErrorAction SilentlyContinue
    $schemeRegistered = ($null -ne $schemeKey) -and ($null -ne $schemeKey.GetValue('{{SCHEME_NAME_ESCAPED}}'))
    if (-not $schemeRegistered) {
        $keepTempDir = $true
        Write-Host 'WARNING: The cursor scheme was not found in the registry after install.' -ForegroundColor Red
        Write-Host '         The installer may have failed silently (check for any error dialogs).' -ForegroundColor Red
        Write-Host "         Temp files kept for inspection: $tempDir" -ForegroundColor Red
    }
    else {
        Write-Host "'{{SCHEME_NAME}}' installed successfully!" -ForegroundColor Green
    }
}
catch {
    $keepTempDir = $true
    Write-Host ''
    Write-Host 'ERROR: Installation failed!' -ForegroundColor Red
    Write-Host $_.Exception.Message -ForegroundColor Red
    if ($null -ne $_.Exception.InnerException) {
        Write-Host "Inner: $($_.Exception.InnerException.Message)" -ForegroundColor Red
    }
    Write-Host ''
    Write-Host "Temp files kept for inspection: $tempDir" -ForegroundColor Yellow
}
finally {
    if (-not $keepTempDir -and (Test-Path $tempDir)) {
        Remove-Item -Recurse -Force $tempDir -ErrorAction SilentlyContinue
    }
}

Read-Host 'Press Enter to exit'
