<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup>
    <Product>Cursor Installer Creator</Product>
    <Company>Der_Floh</Company>
    <Authors>Der_Floh</Authors>
    <Copyright>Copyright © 2023 Der_Floh</Copyright>
    <Version>0.0.0</Version>
    <NeutralLanguage>en</NeutralLanguage>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
</Project>
