name: CI

on:
  push:
    branches: ['**']
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    uses: Der-Floh/Der-Floh/.github/workflows/app-ci.yml@v1
    with:
      projects: >-
        [
        {"name": "desktop", "project": "Cursor_Installer_Creator.Desktop/Cursor_Installer_Creator.Desktop.csproj", "wasm": false},
        {"name": "web", "project": "Cursor_Installer_Creator.Browser/Cursor_Installer_Creator.Browser.csproj", "wasm": true}
        ]
      publish-project: Cursor_Installer_Creator.Desktop/Cursor_Installer_Creator.Desktop.csproj
      publish-profile: winx64
